# Generated by Django 4.0.3 on 2022-03-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portales', '0002_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='url',
            field=models.CharField(max_length=50),
        ),
    ]
