# Generated by Django 4.0.3 on 2022-03-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portales', '0003_alter_design_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='url',
            field=models.URLField(max_length=50),
        ),
    ]
