# Generated by Django 4.0.3 on 2022-03-21 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portales', '0008_alter_page_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='design', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
